"""empty message

Revision ID: 346b8a71171f
Revises: 65e24b9862d2
Create Date: 2024-04-26 20:17:32.681782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '346b8a71171f'
down_revision = '65e24b9862d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_on', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('joined_on')

    # ### end Alembic commands ###
