"""empty message

Revision ID: 4dfb3d47338a
Revises: 346b8a71171f
Create Date: 2024-04-26 20:20:44.013091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dfb3d47338a'
down_revision = '346b8a71171f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.drop_column('joined_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
