"""empty message

Revision ID: cfdcae9b74ac
Revises: 
Create Date: 2024-04-28 11:26:27.281669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdcae9b74ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_post_id_key', type_='unique')
        batch_op.drop_constraint('likes_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('likes_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('likes_post_id_key', ['post_id'])

    # ### end Alembic commands ###
